// <auto-generated />
using System;
using Bravito.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bravito.Infrastructure.Migrations
{
    [DbContext(typeof(BravitoDbContext))]
    [Migration("20260616212411_AdicionaRecursoBaseConhecimento")]
    partial class AdicionaRecursoBaseConhecimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bravito.Domain.Acesso.PerfilAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("perfis_acesso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(4587),
                            Descricao = "Acesso total ao sistema",
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(4667),
                            Descricao = "Acesso a operações diárias e chat",
                            Nome = "Operador"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(4677),
                            Descricao = "Acesso restrito ao chat",
                            Nome = "Somente Chat"
                        });
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.PerfilAcessoRecurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("PerfilAcessoId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_acesso_id");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_id");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("PerfilAcessoId", "RecursoId")
                        .IsUnique();

                    b.ToTable("perfis_acesso_recursos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9297),
                            PerfilAcessoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9382),
                            PerfilAcessoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9386),
                            PerfilAcessoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9389),
                            PerfilAcessoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9393),
                            PerfilAcessoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9397),
                            PerfilAcessoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9400),
                            PerfilAcessoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000101"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9402),
                            PerfilAcessoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000102"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9404),
                            PerfilAcessoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000201"),
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(9408),
                            PerfilAcessoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RecursoId = new Guid("a0000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.Recurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("recursos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            Codigo = "chat.acessar",
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(8182),
                            Descricao = "Permite acessar e enviar mensagens no chat",
                            Nome = "Acessar Chat"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Ativo = true,
                            Codigo = "conversas.visualizar",
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(8301),
                            Descricao = "Permite visualizar histórico de conversas",
                            Nome = "Visualizar Conversas"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Ativo = true,
                            Codigo = "usuarios.visualizar",
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(8305),
                            Descricao = "Permite visualizar lista de usuários",
                            Nome = "Visualizar Usuários"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Ativo = true,
                            Codigo = "usuarios.cadastrar",
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(8307),
                            Descricao = "Permite cadastrar novos usuários",
                            Nome = "Cadastrar Usuários"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Ativo = true,
                            Codigo = "usuarios.editar",
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(8309),
                            Descricao = "Permite editar usuários existentes",
                            Nome = "Editar Usuários"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Ativo = true,
                            Codigo = "usuarios.desativar",
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(8313),
                            Descricao = "Permite desativar/ativar usuários",
                            Nome = "Desativar Usuários"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Ativo = true,
                            Codigo = "base_conhecimento.acessar",
                            DataCriacao = new DateTime(2026, 6, 16, 21, 24, 11, 226, DateTimeKind.Utc).AddTicks(8316),
                            Descricao = "Permite acessar a Base de Conhecimento",
                            Nome = "Acessar Base de Conhecimento"
                        });
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keycloak_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.UsuarioPerfilAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("PerfilAcessoId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_acesso_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PerfilAcessoId");

                    b.HasIndex("UsuarioId", "PerfilAcessoId")
                        .IsUnique();

                    b.ToTable("usuarios_perfis_acesso", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Chat.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CanalOrigem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("canal_origem");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataUltimaInteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_interacao");

                    b.Property<string>("IdentificadorExterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identificador_externo");

                    b.Property<string>("Metadados")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadados");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("conversas", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaContexto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<string>("DadosAuxiliares")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_auxiliares");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<string>("ResumoAtual")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resumo_atual");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId")
                        .IsUnique();

                    b.ToTable("conversas_contextos", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Detalhes")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalhes");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("conversas_eventos", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaMensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<string>("ConteudoBruto")
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo_bruto");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("ModeloUsado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo_usado");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TipoRemetente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_remetente");

                    b.Property<int?>("TokensEntrada")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_entrada");

                    b.Property<int?>("TokensSaida")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_saida");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("conversas_mensagens", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.PerfilAcessoRecurso", b =>
                {
                    b.HasOne("Bravito.Domain.Acesso.PerfilAcesso", "PerfilAcesso")
                        .WithMany("Recursos")
                        .HasForeignKey("PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bravito.Domain.Acesso.Recurso", "Recurso")
                        .WithMany("PerfisAcesso")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.UsuarioPerfilAcesso", b =>
                {
                    b.HasOne("Bravito.Domain.Acesso.PerfilAcesso", "PerfilAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bravito.Domain.Acesso.Usuario", "Usuario")
                        .WithMany("PerfisAcesso")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaContexto", b =>
                {
                    b.HasOne("Bravito.Domain.Chat.Conversa", "Conversa")
                        .WithOne("Contexto")
                        .HasForeignKey("Bravito.Domain.Chat.ConversaContexto", "ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversa");
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaEvento", b =>
                {
                    b.HasOne("Bravito.Domain.Chat.Conversa", "Conversa")
                        .WithMany("Eventos")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversa");
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaMensagem", b =>
                {
                    b.HasOne("Bravito.Domain.Chat.Conversa", "Conversa")
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversa");
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.PerfilAcesso", b =>
                {
                    b.Navigation("Recursos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.Recurso", b =>
                {
                    b.Navigation("PerfisAcesso");
                });

            modelBuilder.Entity("Bravito.Domain.Acesso.Usuario", b =>
                {
                    b.Navigation("PerfisAcesso");
                });

            modelBuilder.Entity("Bravito.Domain.Chat.Conversa", b =>
                {
                    b.Navigation("Contexto");

                    b.Navigation("Eventos");

                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
