// <auto-generated />
using System;
using Bravito.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bravito.Infrastructure.Migrations
{
    [DbContext(typeof(BravitoDbContext))]
    partial class BravitoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bravito.Domain.Chat.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CanalOrigem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("canal_origem");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataUltimaInteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_interacao");

                    b.Property<string>("IdentificadorExterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identificador_externo");

                    b.Property<string>("Metadados")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadados");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("conversas", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaContexto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<string>("DadosAuxiliares")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_auxiliares");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<string>("ResumoAtual")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resumo_atual");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId")
                        .IsUnique();

                    b.ToTable("conversas_contextos", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Detalhes")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalhes");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("conversas_eventos", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaMensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<string>("ConteudoBruto")
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo_bruto");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("ModeloUsado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo_usado");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TipoRemetente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_remetente");

                    b.Property<int?>("TokensEntrada")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_entrada");

                    b.Property<int?>("TokensSaida")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_saida");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("conversas_mensagens", (string)null);
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaContexto", b =>
                {
                    b.HasOne("Bravito.Domain.Chat.Conversa", "Conversa")
                        .WithOne("Contexto")
                        .HasForeignKey("Bravito.Domain.Chat.ConversaContexto", "ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversa");
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaEvento", b =>
                {
                    b.HasOne("Bravito.Domain.Chat.Conversa", "Conversa")
                        .WithMany("Eventos")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversa");
                });

            modelBuilder.Entity("Bravito.Domain.Chat.ConversaMensagem", b =>
                {
                    b.HasOne("Bravito.Domain.Chat.Conversa", "Conversa")
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversa");
                });

            modelBuilder.Entity("Bravito.Domain.Chat.Conversa", b =>
                {
                    b.Navigation("Contexto");

                    b.Navigation("Eventos");

                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
